config/routes.rb
Quackology::Application.routes.draw do
  resources :ducks

end

app/models/duck.rb
class Duck < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ducks_controller.rb
class DucksController < ApplicationController

  before_filter :find_duck, only: [:show, :edit, :update, :destroy]

  # GET /ducks
  # GET /ducks.json
  def index
    @ducks = Duck.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ducks }
    end
  end

  # GET /ducks/1
  # GET /ducks/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @duck }
    end
  end

  # GET /ducks/new
  # GET /ducks/new.json
  def new
    @duck = Duck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @duck }
    end
  end

  # GET /ducks/1/edit
  def edit
  end

  # POST /ducks
  # POST /ducks.json
  def create
    @duck = Duck.new(params[:duck])

    respond_to do |format|
      if @duck.save
        format.html { redirect_to @duck, notice: 'Duck was successfully created.' }
        format.json { render json: @duck, status: :created, location: @duck }
      else
        format.html { render action: "new" }
        format.json { render json: @duck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ducks/1
  # PUT /ducks/1.json
  def update
    respond_to do |format|
      if @duck.update_attributes(params[:duck])
        format.html { redirect_to @duck, notice: 'Duck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @duck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ducks/1
  # DELETE /ducks/1.json
  def destroy
    @duck.destroy

    respond_to do |format|
      format.html { redirect_to ducks_url }
      format.json { head :no_content }
    end
  end

  private

  def find_duck
    @duck = Duck.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ducks_helper.rb
module DucksHelper
end

app/views/ducks/_form.html.erb
<%= form_for(@duck) do |f| %>
  <% if @duck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duck.errors.count, "error") %> prohibited this duck from being saved:</h2>

      <ul>
      <% @duck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ducks/edit.html.erb
<h1>Editing duck</h1>

<%= render 'form' %>

<%= link_to 'Show', @duck %> |
<%= link_to 'Back', ducks_path %>

app/views/ducks/index.html.erb
<h1>Listing ducks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>

  </tr>

<% @ducks.each do |duck| %>
  <tr>
    <td><%= duck.name %></td>
    <td><%= duck.description %></td>
    <td><%= link_to 'Show', duck %></td>
    <td><%= link_to 'Edit', edit_duck_path(duck) %></td>
    <td><%= link_to 'Destroy', duck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Duck', new_duck_path %>

app/views/ducks/new.html.erb
<h1>New duck</h1>

<%= render 'form' %>

<%= link_to 'Back', ducks_path %>

app/views/ducks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @duck.name %>
</p>

<p>
  <b>Description:</b>
  <%= @duck.description %>
</p>


<%= link_to 'Edit', edit_duck_path(@duck) %> |
<%= link_to 'Back', ducks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quackology</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>